### ISSUE TITLE
update readme.md

### ISSUE THREAD

**Issue by berndhopp** [komamitsu/fast-uuid-parser#7]
I think the performance advantage is more like seven times better than UUID.parse now, maybe consider running the benchmark again and reflect the latest results in readme.md

**Comment by komamitsu** [comment]
Hi @berndhopp,

One of the latest benchmarks on Travis CI with Ubuntu 16.04 shows more than 5.5 times faster performance not 7 times faster one.

https://travis-ci.org/github/komamitsu/fast-uuid-parser/jobs/674854501
```
Benchmark                            Mode  Cnt      Score    Error   Units
FastUuidParserBenchmark.fromString  thrpt   20  13001.895 ± 12.659  ops/ms
NormalUUIDBenchmark.fromString      thrpt   20   2363.129 ± 31.584  ops/ms
```
I believe you got the 7 times faster performance on your laptop, but I'll update the performance result in README with the result on Travis CI for now.

**Comment by berndhopp** [comment]
Thank you

**Comment by komamitsu** [comment]
@berndhopp Updated https://github.com/komamitsu/fast-uuid-parser/commit/3b39f360b7867d899b3bd730dce6bd1bb118048b. Thanks for pinging me!
